#!/bin/sh

set -e

case "$1" in
    configure)
        update-python-modules -p # to upstart update code before triggering code reload
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
